In [48]:
import numpy as np

In [49]:
a = np.array([1, 2, 3, 4])
b = np.ones(4)

In [50]:
a

array([1, 2, 3, 4])

In [51]:
b

array([1., 1., 1., 1.])

In [52]:
c = np.outer(b, a)

In [53]:
c

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [56]:
c * c * c

array([[ 1.,  8., 27., 64.],
       [ 1.,  8., 27., 64.],
       [ 1.,  8., 27., 64.],
       [ 1.,  8., 27., 64.]])