In [1]:
import torch

/Users/alexivanov/opt/miniconda3/envs/cs479/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
input_map = torch.randn((32, 32))

In [3]:
input_map

tensor([[-8.7032e-01, -5.0457e-01,  1.0387e+00,  ...,  1.9302e-03,
         -4.8214e-01, -7.2232e-01],
        [-1.6865e-01, -9.5505e-01,  3.5348e-01,  ...,  3.6126e-01,
          7.3612e-01, -1.1741e-01],
        [ 1.8316e+00, -1.8288e+00, -2.2009e+00,  ...,  1.6349e-03,
         -2.6346e-01, -1.0145e+00],
        ...,
        [-1.5435e+00, -1.0375e+00,  8.4892e-01,  ...,  1.4145e+00,
         -7.8212e-01,  1.1362e+00],
        [-2.9051e-01,  2.6979e-01,  1.7225e-01,  ...,  4.0435e-01,
         -3.4157e-01,  1.4429e+00],
        [ 1.0920e-01,  1.3652e-01,  7.6013e-01,  ..., -2.7938e-01,
          2.8736e+00,  8.1823e-02]])

In [4]:
input_map.shape

torch.Size([32, 32])

In [5]:
input_map = input_map[None, None, :, :]

In [6]:
kern = torch.nn.Conv2d(1,1, (3, 3))
kern(input_map).shape

torch.Size([1, 1, 30, 30])

In [7]:
a = torch.tensor([0, 1, 3])

torch.nn.functional.one_hot(a, num_classes=5)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0]])

In [8]:
import numpy as np

In [9]:
a = torch.tensor([[3, 3, 3.0], [4, 5, 6]])
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.sum(a, 1)

tensor([ 9., 15.])

In [10]:
s = torch.nn.Softmax(dim=1)

In [11]:
s(a)

tensor([[0.3333, 0.3333, 0.3333],
        [0.0900, 0.2447, 0.6652]])

In [3]:
a = torch.tensor([[1, 2], [7, 4], [5, 6]])
torch.argmax(a, dim=1)

tensor([1, 1, 1])