In [1]:
import torch

/Users/alexivanov/opt/miniconda3/envs/cs479/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
input_map = torch.randn((32, 32))

In [3]:
input_map

tensor([[-0.8379,  0.2676,  2.1473,  ..., -0.4718, -0.7560,  0.5699],
        [-0.6492,  0.4166,  0.2961,  ...,  0.3543, -1.0758,  0.0159],
        [ 0.3131,  0.3617, -0.9032,  ...,  0.0505, -1.6991, -0.0851],
        ...,
        [-0.1838,  0.3447,  0.2683,  ...,  0.0892,  0.9962,  0.0159],
        [-3.8681,  3.2963,  0.4790,  ...,  0.4107, -0.9120,  0.5240],
        [-1.5845,  0.9180, -0.0878,  ...,  2.0277, -1.0937,  0.1447]])

In [4]:
input_map.shape

torch.Size([32, 32])

In [5]:
input_map = input_map[None, None, :, :]

In [7]:
kern = torch.nn.Conv2d(1,1, (3, 3))
kern(input_map).shape

torch.Size([1, 1, 30, 30])

In [8]:
a = torch.tensor([0, 1, 3])

torch.nn.functional.one_hot(a, num_classes=5)

tensor([[1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0]])

In [21]:
import numpy as np

In [26]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
b = torch.tensor([[1, 2, 3], [4, 5, 6]])
torch.sum(a, 1)

tensor([ 6, 15])